<?php

namespace Database\Seeders;

use App\Models\User;
// use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;



class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        User::factory()->create([
            'name' => 'Filament Admin',
            'email' => 'admin@admin.com',
            'password' => bcrypt('12345admin'),
        ]);
        DB::table('taxes')->insert([
            ['name' => 'IVA', 'percentage' => 10],
            ['name' => 'IVA', 'percentage' => 21],
            ['name' => 'SIN IMPUESTOS', 'percentage' => 0],
        ]);

        DB::table('brands')->insert([
            ['name' => 'APPLE'],
            ['name' => 'SAMSUNG'],
            ['name' => 'XIAOMI'],
            ['name' => 'HUAWEI'],
            ['name' => 'OPPO'],
        ]);

        DB::table('payment_methods')->insert([
            ['name' => 'TARJETA'],
            ['name' => 'EFECTIVO'],
            ['name' => 'TRANSFERENCIA'],
        ]);

        DB::table('document_types')->insert([
            ['name' => 'DNI'],
            ['name' => 'NIE'],
            ['name' => 'PASAPORTE'],
            ['name' => 'OTRO'],
        ]);

        DB::table('statuses')->insert([
            ['name' => 'PENDIENTE'],
            ['name' => 'PENDIENTE DE PIEZA'],
            ['name' => 'ASIGNADO'],
            ['name' => 'COMPLETADO'],
            ['name' => 'CANCELADO'],
        ]);

        DB::table('roles')->insert([
            ['name' => 'ADMIN'],
            ['name' => 'DEPENDIENTE'],
            ['name' => 'TÉCNICO'],
            ['name' => 'ENCARGADO'],
        ]);

        DB::table('types')->insert([
            ['name' => 'PANTALLA'],
            ['name' => 'BATERÍA'],
            ['name' => 'CONECTOR DE CARGA'],
            ['name' => 'FLEX DE CARGA'],
            ['name' => 'FLEX'],
            ['name' => 'LENTE'],
            ['name' => 'TAPA'],
            ['name'=> 'ACCESORIO'],
        ]);

        DB::table('categories')->insert([
            ['name' => 'SERVICIOS', 'tax_id' => 1],
            ['name' => 'PIEZAS', 'tax_id' => 1],
            ['name' => 'ACCESORIOS', 'tax_id' => 1],
            ['name' => 'REACONDICIONADOS', 'tax_id' => 3],
            ['name' => 'PROPINAS', 'tax_id' => 3],
        ]);

        DB::table('device_models')->insert([
            // Apple iPhone models
            ['brand_id' => 1, 'name' => 'IPHONE 16'],
            ['brand_id' => 1, 'name' => 'IPHONE 16 PLUS'],
            ['brand_id' => 1, 'name' => 'IPHONE 16 PRO'],
            ['brand_id' => 1, 'name' => 'IPHONE 16 PRO MAX'],
            ['brand_id' => 1, 'name' => 'IPHONE 15'],
            ['brand_id' => 1, 'name' => 'IPHONE 15 PLUS'],
            ['brand_id' => 1, 'name' => 'IPHONE 15 PRO'],
            ['brand_id' => 1, 'name' => 'IPHONE 15 PRO MAX'],
            ['brand_id' => 1, 'name' => 'IPHONE 14'],
            ['brand_id' => 1, 'name' => 'IPHONE 14 PRO'],
            ['brand_id' => 1, 'name' => 'IPHONE 14 PRO MAX'],
            ['brand_id' => 1, 'name' => 'IPHONE 14 MINI'],
            ['brand_id' => 1, 'name' => 'IPHONE 13'],
            ['brand_id' => 1, 'name' => 'IPHONE 13 PRO'],
            ['brand_id' => 1, 'name' => 'IPHONE 13 PRO MAX'],
            ['brand_id' => 1, 'name' => 'IPHONE 13 MINI'],
            ['brand_id' => 1, 'name' => 'IPHONE 12'],
            ['brand_id' => 1, 'name' => 'IPHONE 12 PRO'],
            ['brand_id' => 1, 'name' => 'IPHONE 12 PRO MAX'],
            ['brand_id' => 1, 'name' => 'IPHONE 12 MINI'],
            ['brand_id' => 1, 'name' => 'IPHONE 11'],
            ['brand_id' => 1, 'name' => 'IPHONE 11 PRO'],
            ['brand_id' => 1, 'name' => 'IPHONE 11 PRO MAX'],
            ['brand_id' => 1, 'name' => 'IPHONE SE (2020)'],
            ['brand_id' => 1, 'name' => 'IPHONE XR'],
            ['brand_id' => 1, 'name' => 'IPHONE XS'],
            ['brand_id' => 1, 'name' => 'IPHONE XS MAX'],
            ['brand_id' => 1, 'name' => 'IPHONE X'],
            ['brand_id' => 1, 'name' => 'IPHONE 8'],
            ['brand_id' => 1, 'name' => 'IPHONE 8 PLUS'],
            ['brand_id' => 1, 'name' => 'IPHONE 7'],
            ['brand_id' => 1, 'name' => 'IPHONE 7 PLUS'],
            ['brand_id' => 1, 'name' => 'IPHONE 6S'],
            ['brand_id' => 1, 'name' => 'IPHONE 6S PLUS'],
            ['brand_id' => 1, 'name' => 'IPHONE 6'],
            ['brand_id' => 1, 'name' => 'IPHONE 6 PLUS'],
            ['brand_id' => 1, 'name' => 'IPHONE SE (1ST GENERATION)'],
            ['brand_id' => 1, 'name' => 'IPHONE 5S'],
            ['brand_id' => 1, 'name' => 'IPHONE 5C'],
            ['brand_id' => 1, 'name' => 'IPHONE 5'],
            ['brand_id' => 1, 'name' => 'IPHONE 4S'],
            ['brand_id' => 1, 'name' => 'IPHONE 4'],
            ['brand_id' => 1, 'name' => 'IPHONE 3GS'],
            ['brand_id' => 1, 'name' => 'IPHONE 3G'],
            ['brand_id' => 1, 'name' => 'IPHONE (1ST GENERATION)'],

            // Apple iPad models
            ['brand_id' => 1, 'name' => 'IPAD PRO 12.9-INCH (5TH GENERATION)'],
            ['brand_id' => 1, 'name' => 'IPAD PRO 11-INCH (3RD GENERATION)'],
            ['brand_id' => 1, 'name' => 'IPAD AIR (4TH GENERATION)'],
            ['brand_id' => 1, 'name' => 'IPAD (9TH GENERATION)'],
            ['brand_id' => 1, 'name' => 'IPAD MINI (6TH GENERATION)'],

            // Samsung models
            ['brand_id' => 2, 'name' => 'GALAXY S21'],
            ['brand_id' => 2, 'name' => 'GALAXY S21 ULTRA'],
            ['brand_id' => 2, 'name' => 'GALAXY S20'],
            ['brand_id' => 2, 'name' => 'GALAXY S20 FE'],
            ['brand_id' => 2, 'name' => 'GALAXY NOTE 20'],
            ['brand_id' => 2, 'name' => 'GALAXY NOTE 20 ULTRA'],
            ['brand_id' => 2, 'name' => 'GALAXY A72'],
            ['brand_id' => 2, 'name' => 'GALAXY A52'],
            ['brand_id' => 2, 'name' => 'GALAXY Z FOLD 3'],
            ['brand_id' => 2, 'name' => 'GALAXY Z FLIP 3'],
            ['brand_id' => 2, 'name' => 'GALAXY M32'],
            ['brand_id' => 2, 'name' => 'GALAXY M12'],
            ['brand_id' => 2, 'name' => 'GALAXY TAB S7'],
            ['brand_id' => 2, 'name' => 'GALAXY TAB A7'],
            ['brand_id' => 2, 'name' => 'GALAXY S10'],
            ['brand_id' => 2, 'name' => 'GALAXY S10+'],
            ['brand_id' => 2, 'name' => 'GALAXY S9'],
            ['brand_id' => 2, 'name' => 'GALAXY S9+'],
            ['brand_id' => 2, 'name' => 'GALAXY A50'],
            ['brand_id' => 2, 'name' => 'GALAXY A30'],

            // Xiaomi models
            ['brand_id' => 3, 'name' => 'MI 11'],
            ['brand_id' => 3, 'name' => 'MI 11 ULTRA'],
            ['brand_id' => 3, 'name' => 'REDMI NOTE 10'],
            ['brand_id' => 3, 'name' => 'REDMI NOTE 10 PRO'],
            ['brand_id' => 3, 'name' => 'REDMI 9'],
            ['brand_id' => 3, 'name' => 'REDMI 9A'],
            ['brand_id' => 3, 'name' => 'REDMI 9C'],
            ['brand_id' => 3, 'name' => 'POCO X3 PRO'],
            ['brand_id' => 3, 'name' => 'POCO F3'],
            ['brand_id' => 3, 'name' => 'MI 10'],
            ['brand_id' => 3, 'name' => 'MI 10T'],
            ['brand_id' => 3, 'name' => 'MI 10T PRO'],
            ['brand_id' => 3, 'name' => 'REDMI NOTE 9'],
            ['brand_id' => 3, 'name' => 'REDMI NOTE 9 PRO'],
            ['brand_id' => 3, 'name' => 'REDMI NOTE 8'],
            ['brand_id' => 3, 'name' => 'REDMI NOTE 8 PRO'],
            ['brand_id' => 3, 'name' => 'MI 9'],
            ['brand_id' => 3, 'name' => 'MI 9T'],
            ['brand_id' => 3, 'name' => 'MI 9T PRO'],
            ['brand_id' => 3, 'name' => 'POCO M3'],

            // Huawei models
            ['brand_id' => 4, 'name' => 'P50 PRO'],
            ['brand_id' => 4, 'name' => 'P40 PRO'],
            ['brand_id' => 4, 'name' => 'P40'],
            ['brand_id' => 4, 'name' => 'MATE 40 PRO'],
            ['brand_id' => 4, 'name' => 'MATE 30 PRO'],
            ['brand_id' => 4, 'name' => 'MATE 30'],
            ['brand_id' => 4, 'name' => 'NOVA 9'],
            ['brand_id' => 4, 'name' => 'NOVA 8'],
            ['brand_id' => 4, 'name' => 'NOVA 7'],
            ['brand_id' => 4, 'name' => 'Y9A'],
            ['brand_id' => 4, 'name' => 'Y8P'],
            ['brand_id' => 4, 'name' => 'Y7A'],
            ['brand_id' => 4, 'name' => 'P30 PRO'],
            ['brand_id' => 4, 'name' => 'P30'],
            ['brand_id' => 4, 'name' => 'P20 PRO'],
            ['brand_id' => 4, 'name' => 'P20'],
            ['brand_id' => 4, 'name' => 'MATE 20 PRO'],
            ['brand_id' => 4, 'name' => 'MATE 20'],
            ['brand_id' => 4, 'name' => 'Y6P'],
            ['brand_id' => 4, 'name' => 'Y5P'],

            // Oppo models
            ['brand_id' => 5, 'name' => 'FIND X3 PRO'],
            ['brand_id' => 5, 'name' => 'FIND X2 PRO'],
            ['brand_id' => 5, 'name' => 'RENO 6 PRO'],
            ['brand_id' => 5, 'name' => 'RENO 6'],
            ['brand_id' => 5, 'name' => 'RENO 5 PRO'],
            ['brand_id' => 5, 'name' => 'RENO 5'],
            ['brand_id' => 5, 'name' => 'A94'],
            ['brand_id' => 5, 'name' => 'A74'],
            ['brand_id' => 5, 'name' => 'A54'],
            ['brand_id' => 5, 'name' => 'A53'],
            ['brand_id' => 5, 'name' => 'A15'],
            ['brand_id' => 5, 'name' => 'A12'],
            ['brand_id' => 5, 'name' => 'F19 PRO'],
            ['brand_id' => 5, 'name' => 'F19'],
            ['brand_id' => 5, 'name' => 'F17 PRO'],
            ['brand_id' => 5, 'name' => 'F17'],
            ['brand_id' => 5, 'name' => 'K9'],
            ['brand_id' => 5, 'name' => 'K7X'],
            ['brand_id' => 5, 'name' => 'RENO 4 PRO'],
            ['brand_id' => 5, 'name' => 'RENO 4'],
        ]);
        DB::table('clients')->insert([
            [
            'document' => '12345678A',
            'name' => 'JUAN',
            'surname' => 'PÉREZ',
            'surname2' => 'GARCÍA',
            'phone_number' => '600123456',
            'phone_number_2' => '600654321',
            'postal_code' => '28001',
            'address' => 'CALLE MAYOR, 1',
            'document_type_id' => 1,
            'created_at' => now(),
            'updated_at' => now(),
            ],
            [
            'document' => '87654321B',
            'name' => 'MARÍA',
            'surname' => 'LÓPEZ',
            'surname2' => null,
            'phone_number' => '610987654',
            'phone_number_2' => null,
            'postal_code' => '28002',
            'address' => 'CALLE GRAN VÍA, 2',
            'document_type_id' => 2,
            'created_at' => now(),
            'updated_at' => now(),
            ],
            [
            'document' => '11223344C',
            'name' => 'CARLOS',
            'surname' => 'MARTÍNEZ',
            'surname2' => 'FERNÁNDEZ',
            'phone_number' => '620123789',
            'phone_number_2' => '620987321',
            'postal_code' => '28003',
            'address' => 'CALLE ALCALÁ, 3',
            'document_type_id' => 3,
            'created_at' => now(),
            'updated_at' => now(),
            ],
        ]);
        DB::table('companies')->insert([
            [
            'cif' => 'A12345678',
            'name' => 'TECH SOLUTIONS',
            'corporate_name' => 'TECH SOLUTIONS S.L.',
            'address' => 'CALLE INNOVACIÓN, 10',
            'postal_code' => '28004',
            'locality' => 'MADRID',
            'province' => 'MADRID',
            'discount' => 0,
            'created_at' => now(),
            'updated_at' => now(),
            ],
            [
            'cif' => 'B87654321',
            'name' => 'GREEN ENERGY',
            'corporate_name' => 'GREEN ENERGY S.A.',
            'address' => 'AVENIDA VERDE, 20',
            'postal_code' => '28005',
            'locality' => 'MADRID',
            'province' => 'MADRID',
            'discount' => 3.0,
            'created_at' => now(),
            'updated_at' => now(),
            ],
            [
            'cif' => 'C11223344',
            'name' => 'SMART DEVICES',
            'corporate_name' => 'SMART DEVICES CORP.',
            'address' => 'PASEO INTELIGENTE, 30',
            'postal_code' => '28006',
            'locality' => 'MADRID',
            'province' => 'MADRID',
            'discount' => 5.0,
            'created_at' => now(),
            'updated_at' => now(),
            ],
        ]);
        DB::table('items')->insert([
            [
            'name' => 'PROTECTOR DE PANTALLA',
            'cost' => 2.5,
            'price' => 10.0,
            'distributor' => 'SUMINISTROS TÉCNICOS S.L.',
            'type_id' => 1,
            'category_id' => 3,
            'created_at' => now(),
            'updated_at' => now(),
            ],
            [
            'name' => 'BATERÍA IPHONE',
            'cost' => 15.0,
            'price' => 50.0,
            'distributor' => 'MUNDO BATERÍAS',
            'type_id' => 2,
            'category_id' => 2,
            'created_at' => now(),
            'updated_at' => now(),
            ],
            [
            'name' => 'CABLE DE CARGA',
            'cost' => 3.0,
            'price' => 15.0,
            'distributor' => 'SOLUCIONES DE CABLES',
            'type_id' => 3,
            'category_id' => 3,
            'created_at' => now(),
            'updated_at' => now(),
            ],
            [
            'name' => 'CARGADOR INALÁMBRICO',
            'cost' => 20.0,
            'price' => 60.0,
            'distributor' => 'CENTRO DE CARGADORES',
            'type_id' => 4,
            'category_id' => 3,
            'created_at' => now(),
            'updated_at' => now(),
            ],
            [
            'name' => 'LENTE DE CÁMARA',
            'cost' => 25.0,
            'price' => 80.0,
            'distributor' => 'EXPERTOS EN LENTES',
            'type_id' => 6,
            'category_id' => 2,
            'created_at' => now(),
            'updated_at' => now(),
            ],
            [
            'name' => 'FUNDA PARA TELÉFONO',
            'cost' => 5.0,
            'price' => 20.0,
            'distributor' => 'FÁBRICA DE FUNDAS',
            'type_id' => 7,
            'category_id' => 3,
            'created_at' => now(),
            'updated_at' => now(),
            ],
            [
            'name' => 'PANTALLA PARA TABLET',
            'cost' => 50.0,
            'price' => 150.0,
            'distributor' => 'MAESTROS DE PANTALLAS',
            'type_id' => 1,
            'category_id' => 2,
            'created_at' => now(),
            'updated_at' => now(),
            ],
            [
            'name' => 'BATERÍA PARA SMARTWATCH',
            'cost' => 10.0,
            'price' => 40.0,
            'distributor' => 'MUNDO BATERÍAS',
            'type_id' => 2,
            'category_id' => 2,
            'created_at' => now(),
            'updated_at' => now(),
            ],
            [
            'name' => 'CABLE USB-C',
            'cost' => 4.0,
            'price' => 12.0,
            'distributor' => 'SOLUCIONES DE CABLES',
            'type_id' => 3,
            'category_id' => 3,
            'created_at' => now(),
            'updated_at' => now(),
            ],
            [
            'name' => 'BATERÍA PORTÁTIL',
            'cost' => 25.0,
            'price' => 70.0,
            'distributor' => 'CENTRO DE CARGADORES',
            'type_id' => 4,
            'category_id' => 3,
            'created_at' => now(),
            'updated_at' => now(),
            ],
            [
            'name' => 'LENTE TRASERA DE CÁMARA',
            'cost' => 30.0,
            'price' => 90.0,
            'distributor' => 'EXPERTOS EN LENTES',
            'type_id' => 6,
            'category_id' => 2,
            'created_at' => now(),
            'updated_at' => now(),
            ],
            [
            'name' => 'AURICULARES INALÁMBRICOS',
            'cost' => 40.0,
            'price' => 120.0,
            'distributor' => 'TECNOLOGÍA DE AUDIO',
            'type_id' => 7,
            'category_id' => 3,
            'created_at' => now(),
            'updated_at' => now(),
            ],
            [
            'name' => 'PANTALLA PARA PORTÁTIL',
            'cost' => 100.0,
            'price' => 300.0,
            'distributor' => 'MAESTROS DE PANTALLAS',
            'type_id' => 1,
            'category_id' => 2,
            'created_at' => now(),
            'updated_at' => now(),
            ],
            [
            'name' => 'BATERÍA PARA SMARTPHONE',
            'cost' => 12.0,
            'price' => 45.0,
            'distributor' => 'MUNDO BATERÍAS',
            'type_id' => 2,
            'category_id' => 2,
            'created_at' => now(),
            'updated_at' => now(),
            ],
            [
            'name' => 'CABLE HDMI',
            'cost' => 6.0,
            'price' => 18.0,
            'distributor' => 'SOLUCIONES DE CABLES',
            'type_id' => 3,
            'category_id' => 3,
            'created_at' => now(),
            'updated_at' => now(),
            ],
            [
            'name' => 'CARGADOR PORTÁTIL',
            'cost' => 30.0,
            'price' => 90.0,
            'distributor' => 'CENTRO DE CARGADORES',
            'type_id' => 4,
            'category_id' => 3,
            'created_at' => now(),
            'updated_at' => now(),
            ],
            [
            'name' => 'LENTE FRONTAL DE CÁMARA',
            'cost' => 20.0,
            'price' => 70.0,
            'distributor' => 'EXPERTOS EN LENTES',
            'type_id' => 6,
            'category_id' => 2,
            'created_at' => now(),
            'updated_at' => now(),
            ],
            [
            'name' => 'ALTAVOZ BLUETOOTH',
            'cost' => 35.0,
            'price' => 100.0,
            'distributor' => 'TECNOLOGÍA DE AUDIO',
            'type_id' => 7,
            'category_id' => 3,
            'created_at' => now(),
            'updated_at' => now(),
            ],
            [
            'name' => 'PANTALLA PARA MONITOR',
            'cost' => 80.0,
            'price' => 250.0,
            'distributor' => 'MAESTROS DE PANTALLAS',
            'type_id' => 1,
            'category_id' => 2,
            'created_at' => now(),
            'updated_at' => now(),
            ],
            [
            'name' => 'BATERÍA PARA TABLET',
            'cost' => 18.0,
            'price' => 60.0,
            'distributor' => 'MUNDO BATERÍAS',
            'type_id' => 2,
            'category_id' => 2,
            'created_at' => now(),
            'updated_at' => now(),
            ],
        ]);

        DB::table('stores')->insert([
            [
            'name' => 'PLAZA MAYOR',
            'address' => 'CALLE REPARACIÓN, 1',
            'work_order_number' => 0,
            'created_at' => now(),
            'updated_at' => now(),
            ],
            [
            'name' => 'POLIGONO SANTA BARBARA',
            'address' => 'CALLE ENERGÍA, 2',
            'work_order_number' => 0,
            'created_at' => now(),
            'updated_at' => now(),
            ],
            [
            'name' => 'VIALIA',
            'address' => 'CALLE CARGA, 3',
            'work_order_number' => 0,
            'created_at' => now(),
            'updated_at' => now(),
            ],
        ]);

        DB::table('repair_times')->insert([
            [
            'name' => '1 HORA',
            'created_at' => now(),
            'updated_at' => now(),
            ],
            [
            'name' => '2 HORAS',
            'created_at' => now(),
            'updated_at' => now(),
            ],
            [
            'name' => '3 HORAS',
            'created_at' => now(),
            'updated_at' => now(),
            ],
            [
            'name' => '2 DAYS',
            'created_at' => now(),
            'updated_at' => now(),
            ],
            [
                'name' => 'SE AVISARÁ CUANDO ENCONTREMOS LA AVERÍA.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'SE AVISARÁ CUANDO LA REPARACION ESTÉ FINALIZADA.',
                'created_at' => now(),
                'updated_at' => now(),
            ],

        ]);


        DB::table('devices')->insert([
            [
                'has_no_serial_or_imei' => false,
                'serial_number' => 'SN1234567890',
                'IMEI' => '123456789012345',
                'colour' => 'Black',
                'unlock_code' => '1234',
                'device_model_id' => 1,
                'client_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'has_no_serial_or_imei' => false,
                'serial_number' => 'SN0987654321',
                'IMEI' => '543210987654321',
                'colour' => 'White',
                'unlock_code' => '5678',
                'device_model_id' => 2,
                'client_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'has_no_serial_or_imei' => true,
                'serial_number' => null,
                'IMEI' => null,
                'colour' => 'Blue',
                'unlock_code' => null,
                'device_model_id' => 3,
                'client_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'has_no_serial_or_imei' => false,
                'serial_number' => 'SN1122334455',
                'IMEI' => '112233445566778',
                'colour' => 'Red',
                'unlock_code' => '4321',
                'device_model_id' => 4,
                'client_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'has_no_serial_or_imei' => false,
                'serial_number' => 'SN5566778899',
                'IMEI' => '998877665544332',
                'colour' => 'Green',
                'unlock_code' => '8765',
                'device_model_id' => 5,
                'client_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'has_no_serial_or_imei' => true,
                'serial_number' => null,
                'IMEI' => null,
                'colour' => 'Yellow',
                'unlock_code' => null,
                'device_model_id' => 6,
                'client_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'has_no_serial_or_imei' => false,
                'serial_number' => 'SN6677889900',
                'IMEI' => '667788990011223',
                'colour' => 'Purple',
                'unlock_code' => '1111',
                'device_model_id' => 7,
                'client_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'has_no_serial_or_imei' => false,
                'serial_number' => 'SN4455667788',
                'IMEI' => '445566778899001',
                'colour' => 'Pink',
                'unlock_code' => '2222',
                'device_model_id' => 8,
                'client_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'has_no_serial_or_imei' => true,
                'serial_number' => null,
                'IMEI' => null,
                'colour' => 'Orange',
                'unlock_code' => null,
                'device_model_id' => 9,
                'client_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'has_no_serial_or_imei' => false,
                'serial_number' => 'SN2233445566',
                'IMEI' => '223344556677889',
                'colour' => 'Gray',
                'unlock_code' => '3333',
                'device_model_id' => 10,
                'client_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'has_no_serial_or_imei' => false,
                'serial_number' => 'SN9988776655',
                'IMEI' => '998877665544332',
                'colour' => 'Silver',
                'unlock_code' => '4444',
                'device_model_id' => 11,
                'client_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'has_no_serial_or_imei' => true,
                'serial_number' => null,
                'IMEI' => null,
                'colour' => 'Gold',
                'unlock_code' => null,
                'device_model_id' => 12,
                'client_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'has_no_serial_or_imei' => false,
                'serial_number' => 'SN3344556677',
                'IMEI' => '334455667788990',
                'colour' => 'Black',
                'unlock_code' => '5555',
                'device_model_id' => 13,
                'client_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'has_no_serial_or_imei' => false,
                'serial_number' => 'SN7766554433',
                'IMEI' => '776655443322110',
                'colour' => 'White',
                'unlock_code' => '6666',
                'device_model_id' => 14,
                'client_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'has_no_serial_or_imei' => true,
                'serial_number' => null,
                'IMEI' => null,
                'colour' => 'Blue',
                'unlock_code' => null,
                'device_model_id' => 15,
                'client_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'has_no_serial_or_imei' => false,
                'serial_number' => 'SN5566778899',
                'IMEI' => '556677889900112',
                'colour' => 'Red',
                'unlock_code' => '7777',
                'device_model_id' => 16,
                'client_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'has_no_serial_or_imei' => false,
                'serial_number' => 'SN1122334455',
                'IMEI' => '112233445566778',
                'colour' => 'Green',
                'unlock_code' => '8888',
                'device_model_id' => 17,
                'client_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'has_no_serial_or_imei' => true,
                'serial_number' => null,
                'IMEI' => null,
                'colour' => 'Yellow',
                'unlock_code' => null,
                'device_model_id' => 18,
                'client_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'has_no_serial_or_imei' => false,
                'serial_number' => 'SN6677889900',
                'IMEI' => '667788990011223',
                'colour' => 'Purple',
                'unlock_code' => '9999',
                'device_model_id' => 19,
                'client_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'has_no_serial_or_imei' => false,
                'serial_number' => 'SN4455667788',
                'IMEI' => '445566778899001',
                'colour' => 'Pink',
                'unlock_code' => '0000',
                'device_model_id' => 20,
                'client_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
        ]);

        DB::table('store_user')->insert([
            [
            'user_id' => 1,
            'store_id' => 1,
            'created_at' => now(),
            'updated_at' => now(),
            ],
            [
            'user_id' => 1,
            'store_id' => 2,
            'created_at' => now(),
            'updated_at' => now(),
            ],
            [
            'user_id' => 1,
            'store_id' => 3,
            'created_at' => now(),
            'updated_at' => now(),
            ],
        ]);

        DB::table('rol_user')->insert([
            [
            'user_id' => 1,
            'rol_id' => 1, // ADMIN
            'created_at' => now(),
            'updated_at' => now(),
            ],
            [
            'user_id' => 1,
            'rol_id' => 2, // DEPENDIENTE
            'created_at' => now(),
            'updated_at' => now(),
            ],
            [
            'user_id' => 1,
            'rol_id' => 3, // TÉCNICO
            'created_at' => now(),
            'updated_at' => now(),
            ],
        ]);
    }
}
